---
# codecov:
#   require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
