# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Build
      run:   sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b .

    - name: Test
      run: ./task test

    - name: Test Summary
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JUnit Tests
        path: report.xml
        reporter: java-junit

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        files: coverage.txt
        fail_ci_if_error: true
